import mongoose from "mongoose";
import { config } from "../config.js";
import { Product } from "../models/product.model.js";
import { appendEventToProduct, verifyProductEventChain } from "../services/event-chain.service.js";

const internalSeederUser = {
  sub: "seed-script",
  role: "internal",
  partnerId: null
};

const productTemplates = [
  { name: "Smartphone X1", ownerPartnerId: "partner-a", statusFlow: ["manufactured", "shipped", "received", "sold"] },
  { name: "Smartwatch S2", ownerPartnerId: "partner-a", statusFlow: ["manufactured", "shipped", "received"] },
  { name: "Laptop Pro 14", ownerPartnerId: "partner-b", statusFlow: ["manufactured", "shipped", "received", "sold"] },
  { name: "Tablet Air 10", ownerPartnerId: "partner-b", statusFlow: ["manufactured", "shipped"] },
  { name: "Router R5", ownerPartnerId: "partner-c", statusFlow: ["manufactured", "shipped", "received", "sold", "recycled"] },
  { name: "Headphones H9", ownerPartnerId: "partner-c", statusFlow: ["manufactured", "shipped", "received", "sold"] },
  { name: "Camera C3", ownerPartnerId: "partner-d", statusFlow: ["manufactured", "shipped", "received"] },
  { name: "Speaker Mini", ownerPartnerId: "partner-d", statusFlow: ["manufactured", "shipped", "received", "sold"] },
  { name: "Gaming Console G2", ownerPartnerId: "partner-e", statusFlow: ["manufactured", "shipped", "received", "sold", "returned", "recycled"] },
  { name: "Drone D4", ownerPartnerId: "partner-e", statusFlow: ["manufactured", "shipped", "received"] }
];

const hoursAgo = (n) => new Date(Date.now() - n * 60 * 60 * 1000);

const seed = async () => {
  await mongoose.connect(config.mongodbUri);

  const createdProducts = [];
  let counter = 1;

  for (const template of productTemplates) {
    const serialNumber = `LW3-${Date.now()}-${counter.toString().padStart(3, "0")}`;

    const product = await Product.create({
      name: template.name,
      ownerPartnerId: template.ownerPartnerId,
      serialNumber,
      currentStatus: template.statusFlow[0],
      metadata: {
        seeded: true,
        batch: "takehome-sample",
        seedIndex: counter
      }
    });

    let eventStep = 0;
    for (const eventType of template.statusFlow) {
      await appendEventToProduct({
        productId: product._id,
        eventType,
        occurredAt: hoursAgo((productTemplates.length - counter + 1) * 12 - eventStep * 2),
        payload: {
          location: `facility-${(counter % 4) + 1}`,
          notes: `${eventType} event generated by seed script`
        },
        user: internalSeederUser
      });
      eventStep += 1;
    }

    createdProducts.push(product);
    counter += 1;
  }

  // Spot-check integrity on a few seeded products.
  const sampleChecks = createdProducts.slice(0, 3);
  for (const product of sampleChecks) {
    const verification = await verifyProductEventChain(product._id);
    if (!verification.isValid) {
      throw new Error(`Seeded chain verification failed for product ${product._id}`);
    }
  }

  // eslint-disable-next-line no-console
  console.log(`Seed complete. Inserted ${createdProducts.length} products with event chains.`);
};

seed()
  .then(async () => {
    await mongoose.disconnect();
    process.exit(0);
  })
  .catch(async (err) => {
    // eslint-disable-next-line no-console
    console.error("Seed failed:", err.message);
    await mongoose.disconnect();
    process.exit(1);
  });
